# Generated by Django 5.1.6 on 2025-02-20 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='staff',
            field=models.OneToOneField(default='552adb7a-79d0-4e1f-9cb5-30c2a0429a19', on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to='birthday.staff'),
            preserve_default=False,
        ),
    ]
