# Generated by Django 5.1.6 on 2025-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_rename_birth_date_birthday_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_number',
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone Number')], default='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('botany', 'Botany'), ('computer_science', 'Computer Science'), ('chemistry', 'Chemistry'), ('cell_biology_and_genetics', 'Cell Biology And Genetics'), ('marine_sciences', 'Marine Sciences'), ('mathematics', 'Mathematics'), ('microbiology', 'Microbiology'), ('physics', 'Physics'), ('statistics', 'Statistics'), ('zoology', 'Zoology')], default='computer_science', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('non_academic', 'Non Academic')], default='academic', max_length=100),
        ),
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
