# Generated by Django 5.1.6 on 2025-02-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_alter_staff_profile_image_url_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='message',
            field=models.TextField(default='Happy Birthday! Wishing you a fantastic day full of joy and success.'),
        ),
    ]
