# Generated by Django 5.1.6 on 2025-02-26 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_alter_notificationtemplate_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='unique_lower_email',
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(db_collation='nocase', max_length=254, unique=True),
        ),
    ]
