# Generated by Django 5.1.6 on 2025-02-26 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_alter_staff_email_staff_unique_lower_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
