# Generated by Django 5.1.6 on 2025-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0010_staff_user_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
